name: "Cachix"
on:
  push:
jobs:
  builds:
    name: Build configuration
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix build .#defaultPackage.x86_64-linux
    - run: |
        cp ./result/bin/server ./server.linux-x86_64
        cp ./result/bin/client ./client.linux-x86_64
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./server.linux-x86_64
          ./client.linux-x86_64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
